name: Test Commits

env:
  GH_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UV_VERSION: "0.5.30"
defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-dev:
    name: Build Test Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Setup Project for Testing
        shell: bash
        run: uv sync --all-extras --no-install-project --frozen
      - name: Run Format Check
        run: uv run ruff format --check
      - name: Run Linter Check
        run: uv run ruff check
      - name: Get Change Type
        id: change_type
        run: |
          if [[ $GITHUB_REF =~ ^/refs/head/([a-z]+)/([0-9]+)_(.*) ]]
          then
              echo ::set-output name=branch_type::pr
              echo ::set-output name=work_id::${BASH_REMATCH[2]}
              echo ::set-output name=work_name::${BASH_REMATCH[3]}
          fi
          if [[ $GITHUB_REF =~ ^/refs/head/release/v([0-9][0-9a-z._]+) ]]
          then
              echo ::set-output name=branch_type::release
              echo ::set-output name=work_id::${BASH_REMATCH[1]}
          fi
          if [[ $GITHUB_REF == /refs/head/main ]]
          then
              echo ::set-output name=branch_type::main
          fi
      - name: Run Work Unit Tests
        if: steps.change_type.outputs.branch_type == 'pr'
        run: uv run pytest -m issue_${{ steps.change_type.work_id }}
      - name: Run Test Suite
        run: uv run pytest --junit-xml=pytest-report.xml --cov=syntrend --cov-fail-under=70 --cov-report=xml
      - name: Publish Test Artifact
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: pytest-report.xml
